version: "3.8"

services:

  backend:
    image: "955603615851.dkr.ecr.eu-central-1.amazonaws.com/com.jlisok/youtube_activity_manager:0.0.1-SNAPSHOT"
    ports:
      - "8080:8080"
    environment:
      DB_HOST: postgres.c117osjk8qat.eu-central-1.rds.amazonaws.com
      DB_PORT: 5432
      DB_NAME: postgres
      DB_USERNAME: postgres
      DB_PASSWORD: ${DB_PASSWORD}
      FRONTEND_URL: https://www.jlisok.pl,https://jlisok.pl,www.jlisok.pl
      AWS_S3_ACCESS_KEY_ID: ${AWS_S3_ACCESS_KEY_ID}
      AWS_S3_SECRET_ACCESS_KEY_ID: ${AWS_S3_SECRET_ACCESS_KEY_ID}
      AWS_REGION: eu-central-1
      AWS_BUCKET_NAME: com.jlisok.youtube-activity-manager.cloud-data
      URL_TO_GOOGLE_CREDENTIALS: ${URL_TO_GOOGLE_CREDENTIALS}
      
    logging:
      driver: awslogs
      options:
        awslogs-region: eu-central-1
        awslogs-group: youtube-activity-manager

  frontend:
    image: "955603615851.dkr.ecr.eu-central-1.amazonaws.com/com.jlisok/youtube_activity_manager_frontend:0.0.1-SNAPSHOT"
    ports:
      - "80:80"
    environment: 
      API_URL: https://jlisok.pl
    logging:
      driver: awslogs
      options:
        awslogs-region: eu-central-1
        awslogs-group: youtube-activity-manager
