version: "3.8"

services:

  backend:
    image: "955603615851.dkr.ecr.eu-central-1.amazonaws.com/com.jlisok/youtube_activity_manager:0.0.1-SNAPSHOT"
    ports:
      - "8080:8080"
    environment:
      DB_HOST: postgres.c117osjk8qat.eu-central-1.rds.amazonaws.com
      DB_PORT: 5432
      DB_NAME: postgres
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      FRONTEND_URL: https://www.jlisok.pl


  frontend:
    image: "955603615851.dkr.ecr.eu-central-1.amazonaws.com/com.jlisok/youtube_activity_manager_frontend:0.0.1-SNAPSHOT"
    ports:
      - "80:80"