name: deployment
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env: 
      EC2_SECRET: ${{ secrets.EC2_KEY }}

    steps:
      - uses: actions/checkout@v2
      
      - name: run deployment
        run: |
          chmod +x ci/deploy.sh
          ./ci/deploy.sh
