name: deployment
on:
  workflow_dispatch:
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    env: 
      EC2_SECRET: ${{ secrets.EC2_KEY }}
      DB_PASSWORD: ${{ secrets.EC2_DB_PASSWORD }}
      AWS_S3_ACCESS_KEY_ID: ${{ secrets.AWS_S3_ACCESS_KEY_ID }}
      AWS_S3_SECRET_ACCESS_KEY_ID: ${{ secrets.AWS_S3_SECRET_ACCESS_KEY_ID }}

    steps:
      - uses: actions/checkout@v2
      
      - name: run deployment
        run: |
          chmod +x ci/deploy.sh
          ./ci/deploy.sh
          

